controller_list:
  - name: fake_arm_controller
    joints:
      - mico_joint_1
      - mico_joint_2
      - mico_joint_3
      - mico_joint_4
      - mico_joint_5
      - mico_joint_6
  - name: fake_gripper_controller
    joints:
      - mico_joint_finger_1
      - mico_joint_finger_2