controller_list:
 - name: joint_velocity_controller
   action_ns: follow_velocity_trajectory
   type: FollowVelocityTrajectory
   default: true
   joints:
     - mico_joint_1
     - mico_joint_2
     - mico_joint_3
     - mico_joint_4
     - mico_joint_5
     - mico_joint_6
